[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.13.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"


# Page redirects

[[redirects]]
from   = "/updates"
to     = "/"
status = 302
force  = true

[[redirects]]
from   = "rss.xml"
to     = "atom.xml"
status = 301
force  = true


# Domain redirects

[[redirects]]
from   = "https://madebyhanno.hannobraun.de/*"
to     = "https://made-by.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://madebyhanno.netlify.app/*"
to     = "https://made-by.braun-odw.eu/:splat"
status = 301
force  = true
