[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.14.1"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[dev]
framework = "#custom"
command = "zola serve"
targetPort = 1111


# Custom headers

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'none'; img-src 'self'; media-src 'self'; script-src 'self'; style-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self' https://*.braun-odw.eu https://static.mailerlite.com"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"


# Page redirects

[[redirects]]
from = "/products"
to = "/products/notebook"
status = 302              # found
force = true

[[redirects]]
from = "/home"
to = "/"
status = 301   # moved permanently
force = true

[[redirects]]
from = "/about"
to = "/"
status = 301    # moved permanently
force = true

[[redirects]]
from = "/fornjot"
to = "/"
status = 301      # moved permanently
force = true

[[redirects]]
from = "/project/*"
to = "/notes/:splat"
status = 301         # moved permanently
force = true

[[redirects]]
from = "/projects/*"
to = "/notes/:splat"
status = 301         # moved permanently
force = true

[[redirects]]
from = "/products/spacer"
to = "/notes/spacer"
status = 301              # moved permanently
force = true

[[redirects]]
from = "/notes/programmatic-cad"
to = "/notes/code-cad-applications"
status = 301                        # moved permanently
force = true


# Feed redirects

[[redirects]]
from = "rss.xml"
to = "atom.xml"
status = 301     # moved permanently
force = true


# API proxy

[[redirects]]
from = "/api/*"
to = "https://api.braun-odw.eu/:splat"
status = 200
force = true
headers = { Authorization = "Basic Wa81oPIR1PtMIJ3cFgkvyCXXeHESx4CV" }


# Secondary domain

[[redirects]]
from = "https://hannobraun.netlify.app/*"
to = "https://hanno.braun-odw.eu/:splat"
status = 301
force = true
