[package]
name    = "backend"
version = "0.1.0"
edition = "2018"


[dependencies]
tracing            = "*"
tracing-subscriber = "*"
warp               = "*"

[dependencies.tokio]
version  = "*"
features = ["full"]
