[package]
name    = "spacer"
version = "0.1.0"
edition = "2018"

[dependencies]
libfive = "*"

[patch.crates-io.libfive-sys]
git    = "https://github.com/hannobraun/libfive-rs.git"
branch = "libfive-submodule"
