[package]
name    = "mbh" # short for "Made by Hanno"
version = "0.1.0"
edition = "2018"


[dependencies]
anyhow = "*"
clap   = "3.0.0-beta.4"

[dependencies.time]
version  = "*"
features = ["macros", "formatting"]
