[package]
name    = "hbo" # short for `hanno.braun-odw.eu
version = "0.1.0"
edition = "2018"


[dependencies]
anyhow = "*"

[dependencies.clap]
version  = "3.0.0-rc.4"
features = ["derive"]

[dependencies.time]
version  = "*"
features = ["macros", "formatting"]
