title    = "Hanno Braun"
base_url = "https://hanno.braun-odw.eu"

compile_sass  = true
generate_feed = true

highlight_code     = false
build_search_index = false

[slugify]
paths = "safe"

[extra.pages]
Home = "/home"
About = "/about"
Updates = "/updates"
Notes = "/notes"
Services = "/services"
Products = "/products"
Contact = "/contact"
