title    = "Hanno Braun"
base_url = "https://hanno.braun-odw.eu"

compile_sass       = true
highlight_code     = false
build_search_index = false

generate_feed = true
feed_filename = "atom.xml" # need to add custom template before changing

[slugify]
paths = "safe"

[extra.pages]
Home      = "/home"
About     = "/about"
Updates   = "/updates"
Notes     = "/notes"
Services  = "/services"
Products  = "/products"
Contact   = "/contact"
Subscribe = "/subscribe"
