[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.13.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[dev]
framework  = "#custom"
command    = "zola serve"
targetPort = 1111


# Page redirects

[[redirects]]
from   = "/"
to     = "/projects"
status = 307 # temporary redirect
force  = true

[[redirects]]
from   = "/project/*"
to     = "/projects/:splat"
status = 301 # moved permanently
force  = true

[[redirects]]
from   = "rss.xml"
to     = "atom.xml"
status = 301 # moved permanently
force  = true


# Domain redirects

[[redirects]]
from   = "https://madeby.hannobraun.de/*"
to     = "https://made-by.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://madebyhanno.netlify.app/*"
to     = "https://made-by.braun-odw.eu/:splat"
status = 301
force  = true
