[build]
publish = "_site"
command = "./scripts/build"

[build.environment]
ZOLA_VERSION = "0.14.1"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[dev]
framework  = "#custom"
command    = "./scripts/serve.sh"
targetPort = 3000


# Custom headers

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self' https://*.braun-odw.eu https://*.sibforms.com"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[[headers]]
  for = "/.well-known/matrix/client"
  [headers.values]
    Access-Control-Allow-Origin = "*"


# Page redirects

[[redirects]]
from   = "/"
to     = "/updates"
status = 302 # temporary redirect
force  = true

[[redirects]]
from   = "/products"
to     = "/products/spacer"
status = 302 # temporary redirect
force  = true

[[redirects]]
from   = "/project/*"
to     = "/notes/:splat"
status = 301 # moved permanently
force  = true

[[redirects]]
from   = "/projects/*"
to     = "/notes/:splat"
status = 301 # moved permanently
force  = true

[[redirects]]
from   = "rss.xml"
to     = "atom.xml"
status = 301 # moved permanently
force  = true


# API proxy

[[redirects]]
from   = "/api/*"
to     = "https://api.braun-odw.eu/:splat"
status = 200
force  = true
headers = { Authorization = "Basic Wa81oPIR1PtMIJ3cFgkvyCXXeHESx4CV" }


# Secondary domains

[[redirects]]
from   = "https://braun-odw.eu/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.braun-odw.eu/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://hannobraun.netlify.app/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true


# Legacy domains

[[redirects]]
from   = "https://hannobraun.de/"
to     = "https://hanno.braun-odw.eu/"
status = 301
force  = true

[[redirects]]
from   = "https://hannobraun.de/*"
to     = "https://archive.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.hannobraun.de/*"
to     = "https://hannobraun.de/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://madeby.hannobraun.de/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://made-by.braun-odw.eu/*"
to     = "https://hanno.braun-odw.eu/:splat"
status = 301
force  = true
