[package]
name    = "model-api"
version = "0.1.0"
edition = "2018"


[dependencies]
axum               = "*"
tracing            = "*"
tracing-subscriber = "*"

[dependencies.tokio]
version  = "*"
features = ["full"]

[dependencies.tower-http]
version  = "*"
features = ["trace"]
